server:
  port: 8891
spring:
  application:
    name: ms-admin-api-gateway
#  boot:
#    admin:
#      discovery:
#        ignored-services: gateway-service

# Registry Client
eureka:
   client:
      registryFetchIntervalSeconds: 5
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka


